name: build .Net and Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # .net ci/cd

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        dotnet-quality: 'ga'

    - name: Restore .NET dependencies
      working-directory: ./CSharp
      run: dotnet restore aoc2024.csproj

    - name: Build .NET
      working-directory: ./CSharp
      run: dotnet build aoc2024.csproj --no-restore --configuration Release

    - name: Test .NET
      working-directory: ./CSharp
      run: dotnet test aoc2024.csproj --no-build --verbosity normal --configuration Release

    # Rust ci/cd

    - name: Build Rust
      working-directory: ./Rust
      run: cargo build -vv

    - name: Test Rust
      working-directory: ./Rust
      run: cargo test -vv -- --nocapture

